config/routes.rb
Rails.application.routes.draw do
  resources :brews
  get 'brews/:id/edit_mash_g' => 'brews#edit_mash_g', as: :edit_mash_g
  get 'brews/:id/edit_pre_boil_g' => 'brews#edit_pre_boil_g', as: :edit_pre_boil_g
  get 'brews/:id/edit_final_g' => 'brews#edit_final_g', as: :edit_final_g
  get 'brews/:id/edit_pre_keg_g' => 'brews#edit_pre_keg_g', as: :edit_pre_keg_g
  get 'brews/:id/edit_mash_temp' => 'brews#edit_mash_temp', as: :edit_mash_temp
  get 'brews/:id/edit_mash_time' => 'brews#edit_mash_time', as: :edit_mash_time
  get 'brews/:id/edit_boil_time' => 'brews#edit_boil_time', as: :edit_boil_time
  get 'brews/:id/edit_notes' => 'brews#edit_notes', as: :edit_notes
  resources :ingredients
  devise_for :users
 root to: 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brew.rb
class Brew < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,  :lockable, :timeoutable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
end

app/controllers/brews_controller.rb
class BrewsController < ApplicationController
  before_action :set_brew, only: [:show, :edit, :update, :edit_mash_g, :destroy]

  # GET /brews
  # GET /brews.json
  def index
    @brews = Brew.all
  end

  # GET /brews/1
  # GET /brews/1.json
  def show
  end

  # GET /brews/new
  def new
    @brew = Brew.new
  end

  # GET /brews/1/edit
  def edit
  end

  def edit_mash_g

  end

  def edit_notes
    @brew = Brew.find(params[:id])
  end

  def edit_pre_boil_g
    @brew = Brew.find(params[:id])
  end

  def edit_pre_keg_g
    @brew = Brew.find(params[:id])
  end

  def edit_final_g
    @brew = Brew.find(params[:id])
  end

  def edit_mash_temp
    @brew = Brew.find(params[:id])
  end

  def edit_mash_time
    @brew = Brew.find(params[:id])
  end

  def edit_boil_time
    @brew = Brew.find(params[:id])
    end

  # POST /brews
  # POST /brews.json
  def create
    @brew = Brew.new(brew_params)

    respond_to do |format|
      if @brew.save
        format.html { redirect_to @brew, notice: 'Brew was successfully created.' }
        format.json { render :show, status: :created, location: @brew }
      else
        format.html { render :new }
        format.json { render json: @brew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brews/1
  # PATCH/PUT /brews/1.json
  def update
    respond_to do |format|
      if @brew.update(brew_params)
        format.html { redirect_to @brew, notice: 'Brew was successfully updated.' }
        format.json { render :show, status: :ok, location: @brew }
      else
        format.html { render :edit }
        format.json { render json: @brew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brews/1
  # DELETE /brews/1.json
  def destroy
    @brew.destroy
    respond_to do |format|
      format.html { redirect_to brews_url, notice: 'Brew was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brew
      @brew = Brew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brew_params
      params.require(:brew).permit(:date, :name, :mash_gravity, :mash_temp, :mash_time, :boil_time, :pre_boil_gravity, :pre_keg_gravity, :final_gravity, :notes)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brews_helper.rb
module BrewsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brews/_form.html.erb
<%= form_with(model: brew, local: true) do |form| %>
  <% if brew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

      <ul>
      <% brew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brews/edit.html.erb
<h1>Editing Brew</h1>

<%= render 'form', brew: @brew %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/edit_boil_time.html.erb
<h1>Editing Brew</h1>

<%= form_with(model: @brew, local: true) do |form| %>
    <% if @brew.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

          <ul>
            <% @brew.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= form.label :boil_time %>
      <%= form.text_field :boil_time %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/edit_final_g.html.erb
<h1>Editing Brew</h1>

<%= form_with(model: @brew, local: true) do |form| %>
    <% if @brew.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

          <ul>
            <% @brew.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= form.label :final_gravity %>
      <%= form.text_field :final_gravity %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/edit_mash_g.html.erb
<h1>Editing Brew</h1>

<%= form_with(model: @brew, local: true) do |form| %>
    <% if @brew.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

          <ul>
            <% @brew.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= form.label :mash_gravity %>
      <%= form.text_field :mash_gravity %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/edit_mash_temp.html.erb
<h1>Editing Brew</h1>

<%= form_with(model: @brew, local: true) do |form| %>
    <% if @brew.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

          <ul>
            <% @brew.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= form.label :mash_temp %>
      <%= form.text_field :mash_temp %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/edit_mash_time.html.erb
<h1>Editing Brew</h1>

<%= form_with(model: @brew, local: true) do |form| %>
    <% if @brew.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

          <ul>
            <% @brew.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= form.label :mash_time %>
      <%= form.text_field :mash_time %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/edit_notes.html.erb
<h1>Editing notes</h1>

<%= form_with(model: @brew, local: true) do |form| %>
    <% if @brew.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

          <ul>
            <% @brew.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= form.label :notes %>
      <%= form.text_area :notes %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/edit_pre_boil_g.html.erb
<h1>Editing Brew</h1>

<%= form_with(model: @brew, local: true) do |form| %>
    <% if @brew.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

          <ul>
            <% @brew.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= form.label :pre_boil_gravity %>
      <%= form.text_field :pre_boil_gravity %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/edit_pre_keg_g.html.erb
<h1>Editing Brew</h1>

<%= form_with(model: @brew, local: true) do |form| %>
    <% if @brew.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

          <ul>
            <% @brew.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= form.label :pre_keg_gravity %>
      <%= form.text_field :pre_keg_gravity %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brews</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Mash Temp</th>
      <th>Mash Time</th>
      <th>Boil Time</th>
      <th>Mash G</th>
      <th>Pre Boil G</th>
      <th>Original G</th>
      <th>Final G</th>


    </tr>
  </thead>

  <tbody>
    <% @brews.each do |brew| %>
      <tr>
        <td><%=  brew.date %></td>
        <td><%= link_to brew.name, brew %></td>
        <td><%= brew.mash_temp %></td>
        <td><%= brew.mash_time %></td>
        <td><%= brew.boil_time %></td>
        <td><%= brew.mash_gravity %></td>
        <td><%= brew.pre_boil_gravity %></td>
        <td><%= brew.pre_keg_gravity %></td>
        <td><%= brew.final_gravity %></td>


        <td><%= ((  brew.final_gravity - brew.pre_keg_gravity) * 131.25).abs.round(1) unless brew.pre_keg_gravity == nil || brew.final_gravity == nil %></td>
        <td><%= link_to 'Edit', edit_brew_path(brew) %></td>
        <td><%= link_to 'Destroy', brew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brew', new_brew_path %>

app/views/brews/new.html.erb
<h1>New Brew</h1>

<%= render 'form', brew: @brew %>

<%= link_to 'Back', brews_path %>

app/views/brews/show.html.erb
<div class="container-fluid">
  <h1 class="text-center"><%= @brew.name %></h1>
  <h3 class="text-center"><%= @brew.date.strftime("%m/%d/%Y")  %></h3>


  <div class="row">





    <div class="col-sm-3">
    <div class="card text-white bg-secondary mb-3 ">
      <div class="card-body">
        <h5 class="card-title text-center">Mash Temp</h5>
        <p class="card-text"> <% if @brew.mash_temp == nil %>
              <%= form_with(model: @brew, local: true) do |form| %>
                  <%= form.text_field :mash_temp, style: 'width:100%;' %><%= form.submit 'Add' %>
              <% end %>
          <% else %>
            <h4 class="text-center"><%=  @brew.mash_temp %></h4>
            <%=  link_to 'Edit', edit_mash_temp_path %>
        <% end %>

      </div>
    </div>
  </div>

    <div class="col-sm-3">
      <div class="card text-white bg-secondary mb-3 ">
        <div class="card-body">
          <h5 class="card-title text-center">Mash Time</h5>
          <p class="card-text"> <% if @brew.mash_time == nil %>
                <%= form_with(model: @brew, local: true) do |form| %>
                    <%= form.text_field :mash_time, style: 'width:100%;' %><%= form.submit 'Add' %>
                <% end %>
            <% else %>
              <h4 class="text-center"><%=  @brew.mash_time %> Minutes</h4>
              <%=  link_to 'Edit', edit_mash_time_path %>
          <% end %>

        </div>
      </div>
    </div>

    <div class="col-sm-3">
      <div class="card text-white bg-secondary mb-3 ">
        <div class="card-body">
          <h5 class="card-title text-center">Mash Gravity</h5>
          <p class="card-text"> <% if @brew.mash_gravity == nil %>
                <%= form_with(model: @brew, local: true) do |form| %>
                    <%= form.text_field :mash_gravity, style: 'width:100%;' %><%= form.submit 'Add' %>
                <% end %>
            <% else %>
                <h4 class="text-center"><%=  @brew.mash_gravity %></h4>
                <%=  link_to 'Edit', edit_mash_g_path %>
            <% end %>

        </div>
      </div>
    </div>

    <div class="col-sm-3">
      <div class="card text-white bg-secondary mb-3 ">
        <div class="card-body">
          <h5 class="card-title text-center">Pre Boil Gravity</h5>
          <p class="card-text"> <% if @brew.pre_boil_gravity == nil %>
                <%= form_with(model: @brew, local: true) do |form| %>
                    <%= form.text_field :pre_boil_gravity, style: 'width:100%;' %><%= form.submit 'Add' %>
                <% end %>
            <% else %>
              <h4 class="text-center"><%=  @brew.pre_boil_gravity %></h4>
              <%=  link_to 'Edit', edit_pre_boil_g_path %>
          <% end %>

        </div>
      </div>
    </div>

    <div class="col-sm-3">
      <div class="card text-white bg-secondary mb-3 ">
        <div class="card-body">
          <h5 class="card-title text-center">Boil Time</h5>
          <p class="card-text"> <% if @brew.boil_time == nil %>
                <%= form_with(model: @brew, local: true) do |form| %>
                    <%= form.text_field :boil_time, style: 'width:100%;' %><%= form.submit 'Add' %>
                <% end %>
            <% else %>
              <h4 class="text-center"><%=  @brew.boil_time %> Minutes</h4>
              <%=  link_to 'Edit', edit_boil_time_path %>
          <% end %>

        </div>
      </div>
    </div>

    <div class="col-sm-3">
      <div class="card text-white bg-secondary mb-3 ">
        <div class="card-body">
          <h5 class="card-title text-center">Pre Keg Gravity</h5>
          <p class="card-text"> <% if @brew.pre_keg_gravity == nil %>
                <%= form_with(model: @brew, local: true) do |form| %>
                    <%= form.text_field :pre_keg_gravity, style: 'width:100%;' %><%= form.submit 'Add' %>
                <% end %>
            <% else %>
              <h4 class="text-center"><%=  @brew.pre_keg_gravity %></h4>
              <%=  link_to 'Edit', edit_pre_keg_g_path %>
          <% end %>

        </div>
      </div>
    </div>

    <div class="col-sm-3">
    <div class="card text-white bg-secondary mb-3 ">
      <div class="card-body">
        <h5 class="card-title text-center">Final Gravity</h5>
        <p class="card-text"> <% if @brew.final_gravity == nil %>
              <%= form_with(model: @brew, local: true) do |form| %>
                  <%= form.text_field :final_gravity, style: 'width:100%;' %><%= form.submit 'Add' %>
              <% end %>
          <% else %>
            <h4 class="text-center"><%=  @brew.final_gravity %></h4>
            <%=  link_to 'Edit', edit_final_g_path %>
        <% end %>

      </div>
    </div>
  </div>

    <div class="col-sm-3">
      <div class="card text-white bg-secondary mb-3 ">
        <div class="card-body">
          <h5 class="card-title text-center">Alcohol Percentage</h5>
          <h4 class="card-text text-center">
            <%= ((  @brew.final_gravity - @brew.pre_keg_gravity) * 131.25).abs.round(1) unless @brew.pre_keg_gravity == nil || @brew.final_gravity == nil %>
              %
          </h4>
          <br>
        </div>
      </div>
    </div>





    </div>
  </div>
  <!--***************************** end of row ********************************-->
  <div class="row">
    <div class="col-sm-6" style="margin:auto">
      <div class="card text-white bg-secondary mb-3 ">
        <div class="card-body">
          <h5 class="card-title text-center">Final Gravity</h5>
          <p class="card-text"> <% if @brew.notes == nil %>
                <%= form_with(model: @brew, local: true) do |form| %>
                    <%= form.text_area :notes, style: 'width:100%;' %>
                    <br><%= form.submit 'Add' %>
                <% end %>
            <% else %>
              <h4 class="text-center"><%=  @brew.notes %></h4>
              <%=  link_to 'Edit', edit_notes_path %>
          <% end %>

        </div>
      </div>
    </div>
  <





</div>

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

    <div class="field">
      <%= form.label :quantity %>
      <%= form.text_field :quantity %>
      <%= form.select :measurement, ['Gram', 'Ounce', 'Pound'], :selected => 'choose' %>
    </div>


    <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.price %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<div class="container">

<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

</div>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ingredient.price %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand navbar-left" ><%=  link_to 'BEER', root_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item nav-link active">
        <%= link_to 'BREWS', brews_path %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'CALCULATOR', root_path %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'INGREDIENTS', ingredients_path %>
      </li>
      <!--<li class="nav-item nav-link">-->
        <!--<a class="nav-link disabled" href="#">Disabled</a>-->
      <!--</li>-->
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/top_nav' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<div class="container">
  <h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>
</div>